### ISSUE TITLE
SIGSEGV error

### ISSUE THREAD

**Issue by leepro** [RoaringBitmap/gocroaring#13]
I ran some modified version of test code mentioned in README.md. From time to time(not always), it gave the following error. I included the test go code in the below. I used go1.10.1 and it ran on Ubuntu 16 (4.4.0-119-generic)/Intel(R) Core(TM) i7-6700T CPU @ 2.80GHz.

```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x16851f0 pc=0x47297a]

runtime stack:
runtime.throw(0x4b3964, 0x2a)
	/opt/go/src/runtime/panic.go:616 +0x81
runtime.sigpanic()
	/opt/go/src/runtime/signal_unix.go:372 +0x28e

goroutine 1 [syscall]:
runtime.cgocall(0x46a720, 0xc420050e70, 0x151e550)
	/opt/go/src/runtime/cgocall.go:128 +0x64 fp=0xc420050e40 sp=0xc420050e08 pc=0x4088e4
github.com/RoaringBitmap/gocroaring._Cfunc_roaring_bitmap_portable_serialize(0x151e550, 0xc420500000, 0x0)
	_cgo_gotypes.go:589 +0x4e fp=0xc420050e70 sp=0xc420050e40 pc=0x468f3e
github.com/RoaringBitmap/gocroaring.(*Bitmap).Write.func1(0x151e550, 0xc420500000, 0xc420500000)
	/opt/go/.go/src/github.com/RoaringBitmap/gocroaring/gocroaring.go:301 +0x60 fp=0xc420050ea8 sp=0xc420050e70 pc=0x469b50
github.com/RoaringBitmap/gocroaring.(*Bitmap).Write(0xc42000e010, 0xc420500000, 0x14ab70, 0x14ab70, 0x14ab70, 0x14ab70)
	/opt/go/.go/src/github.com/RoaringBitmap/gocroaring/gocroaring.go:301 +0x62 fp=0xc420050ed0 sp=0xc420050ea8 pc=0x469492
main.T()
	/home/test/gocroaring0.go:26 +0x120 fp=0xc420050f28 sp=0xc420050ed0 pc=0x469fb0
main.main()
	/home/test/gocroaring0.go:13 +0x10d fp=0xc420050f88 sp=0xc420050f28 pc=0x469e4d
runtime.main()
	/opt/go/src/runtime/proc.go:198 +0x212 fp=0xc420050fe0 sp=0xc420050f88 pc=0x42cbe2
runtime.goexit()
	/opt/go/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc420050fe8 sp=0xc420050fe0 pc=0x451321
exit status 2
```

```
package main

import (
	"math/rand"
	"time"

	"github.com/RoaringBitmap/gocroaring"
)

func main() {
	rand.Seed(time.Now().UTC().UnixNano())
	for i := 0; i < 1000; i++ {
		T()
	}
}

func T() {
	r0 := gocroaring.New()
	var j uint32
	for i := 0; i < 10000000; i++ {
		j = uint32(rand.Intn(10000000))
		r0.Add(j)
	}
	r0.RunOptimize() // improves compression
	buf0 := make([]byte, r0.SerializedSizeInBytes()+100000)
	r0.Write(buf0) // we omit error handling
}
```

**Comment by lemire** [comment]
Thank you. I will look into it. Meanwhile, if you need Roaring in Go, I recommend https://github.com/RoaringBitmap/roaring as it is actually used in production at major corporations.

**Comment by lemire** [comment]
This is still on my todo.

**Comment by lemire** [comment]
Ok. I cannot verify the issue. I added a test:

https://github.com/RoaringBitmap/gocroaring/blob/master/gocroaring_test.go#L27-L41

But it passes (after I wrote it properly, initial version was a mess).

It would be best if you could provide a deterministic test that fails consistently. Since our code is single-threaded and deterministic, it should be possible to make it fail deterministically.

Reopen if needed.
